version: "3.8"
name: vitals

services:

  # PostgreSQL database for Patient Service
  patient-db:
    image: postgres:17
    container_name: patient-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patientdb
    ports:
      - "5432:5432"
    volumes:
      - patient-db-data:/var/lib/postgresql/data


  # Example: PostgreSQL database for another service in the future
  # billing-db:
  #   image: postgres:17
  #   container_name: billing-db
  #   environment:
  #     POSTGRES_USER: billing_user
  #     POSTGRES_PASSWORD: billing_password
  #     POSTGRES_DB: billingdb
  #   ports:
  #     - "5433:5432"   # Host port changes, container port stays 5432
  #   volumes:
  #     - billing-db-data:/var/lib/postgresql/data


volumes:

  # Persistent storage for patient database
  patient-db-data:

  # Persistent storage for billing database (future)
  # billing-db-data: